# Generated by Django 5.0.2 on 2024-02-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_DB',
            fields=[
                ('bookno', models.IntegerField(primary_key='bookno', serialize=False)),
                ('bookname', models.CharField(max_length=20)),
                ('authorname', models.CharField(max_length=25)),
                ('bookrate', models.IntegerField()),
                ('rating', models.CharField(max_length=20)),
            ],
        ),
    ]
