# Generated by Django 5.0.2 on 2024-02-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_db',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
